require('config.colorscheme')
-- require('config.compe')
-- require('config.indent_blankline')
require('config.lightline')
-- require('config.lspconfig')
-- require('config.lspkind')
-- require('config.nvim-autopairs')
require('config.rust')
require('config.settings')
require('config.telescope')
require('config.treesitter')
-- require('config.nvimTree')
