require('config.cmp')
require('config.colorscheme')
require('config.lightline')
require('config.lspconfig')
-- require('config.lspkind')
-- require('config.nvim-autopairs')
require('config.nvim-tree')
require('config.rust')
require('config.settings')
require('config.telescope')
require('config.treesitter')
